# ===========================================================
# NAVIGATION
# ===========================================================

nav:
  - Home: README.md
  - My apps: pages/my-apps.md
  - About: about.md
  - Docs: https://docs.alnoda.org/ruby-workspace/

# ===========================================================
# CONFIGURATION
# ===========================================================

site_name: Ruby workspace
repo_url: https://github.com/bluxmit/alnoda-workspaces
site_url: https://docs.alnoda.org
edit_uri: ""

# ===========================================================
# APPEARANCE
# ===========================================================

theme:
  name: 'material'
  favicon: 'assets/ruby-circle.svg'
  logo: 'assets/ruby-circle-white.svg'
  custom_dir: overrides
  font:
    text: Noto Sans
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
  palette:
    - scheme: ruby-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode 
    - scheme: ruby
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra:
  # Link to open when your logo is clicked
  homepage: https://docs.alnoda.org
  host_url: http://docs.alnoda.org

plugins:
  # Enable Macros and jinja2 templates
  - macros:
      module_name: macros/helpers

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6

